{
 "title": "K8s Monitoring",
 "description": "NISLAB",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Teastore Container CPU Usage (Default Namespace)",
   "type": "timeseries",
   "description": "% utilization of available CPU\n(CPU seconds/second) / [available](CPU seconds/second)",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='default'}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Teastore Container CPU Usage (Default Namespace)",
   "type": "timeseries",
   "description": "% utilization of available CPU\n(CPU seconds/second) / [available](CPU seconds/second)",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='default'}[1m])) by (pod_name, container_name)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Teastore Containers Count (Default Namespace)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"default\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Teastore Memory Usage (Default Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_memory_working_set_bytes{namespace=\"default\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitoring Stack CPU Usage (Monitoring Namespace)",
   "type": "timeseries",
   "description": "CPU seconds",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"monitoring\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Monitoring Stack Memory Usage (Monitoring Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_memory_working_set_bytes{namespace=\"monitoring\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "timeseries",
   "description": "CPU seconds",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Monitoring Stack Memory Usage (Monitoring Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_memory_working_set_bytes[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}