apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: coinflipmetrics.example.com
spec:
    group: example.com
    versions:
        - name: v1
          served: true
          storage: true
          schema:
              openAPIV3Schema:
                  type: object
                  properties:
                      spec:
                          type: object
                          properties:
                              value:
                                  type: integer
                                  minimum: 0
                                  maximum: 1
    scope: Namespaced
    names:
        plural: coinflipmetrics
        singular: coinflipmetric
        kind: CoinFlipMetric
        shortNames:
            - cfm
