apiVersion: v1
kind: Service
metadata:
#  annotations:
#    prometheus.io/path: /metrics
#    prometheus.io/port: "80"
#    prometheus.io/scrape: "true"
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  clusterIP: 10.152.183.190
  clusterIPs:
  - 10.152.183.190
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32428
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}