{
 "title": "NISLAB Monitoring",
 "description": "NISLAB",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Service Units (SU) Used",
   "type": "timeseries",
   "description": "https://nerc-project.github.io/nerc-docs/get-started/cost-billing/how-pricing-works/",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "SU" } },
   "targets": [
    {
     "expr": "ceil(\r\n  max(\r\n    sum(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[1m])) >\r\n    sum(container_memory_working_set_bytes{namespace='default'} / (4 * 1024 * 1024 * 1024)) or\r\n    sum(container_memory_working_set_bytes{namespace='default'} / (4 * 1024 * 1024 * 1024))\r\n  )\r\n)",
     "legendFormat": "Max between CPU and Memory Usage"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[1m]))",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace='default'} / (4 * 1024 * 1024 * 1024))",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Max Service Units (SU) Used",
   "type": "gauge",
   "description": "https://nerc-project.github.io/nerc-docs/get-started/cost-billing/how-pricing-works/",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "SU" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "ceil(\r\n  max(\r\n    sum(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[1m])) or\r\n    sum(container_memory_working_set_bytes{namespace='default'} / (4 * 1024 * 1024 * 1024))\r\n  )\r\n)",
     "legendFormat": "Max between CPU and Memory Usage"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[1m]))",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace='default'} / (4 * 1024 * 1024 * 1024))",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Teastore Containers Count (Default Namespace)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"default\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Teastore Container CPU Usage (Default Namespace)",
   "type": "timeseries",
   "description": "% utilization of available CPU\n(CPU seconds/second) / [available](CPU seconds/second)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='default'}[1m])) by (namespace)",
     "legendFormat": "Teastore (all)"
    }
   ]
  },
  {
   "title": "Teastore Memory Usage (Default Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (rate(container_memory_working_set_bytes{namespace=\"default\"}[1m])) by (namespace) ",
     "legendFormat": "Teastore (all)"
    }
   ]
  },
  {
   "title": "Teastore Container CPU Usage (Default Namespace)",
   "type": "timeseries",
   "description": "% utilization of available CPU\n(CPU seconds/second) / [available](CPU seconds/second)",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='default'}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Teastore Memory Usage (Default Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_memory_working_set_bytes{namespace=\"default\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitoring Stack CPU Usage (Monitoring Namespace)",
   "type": "timeseries",
   "description": "CPU seconds",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"monitoring\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Monitoring Stack Memory Usage (Monitoring Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"monitoring\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "timeseries",
   "description": "CPU seconds",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod!=\"\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod!=''})",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}