{
 "title": "NISLAB Monitoring",
 "description": "NISLAB",
 "time": { "from": "2024-12-16T22:44:51.205Z", "to": "2024-12-16T23:13:50.666Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Rate of requests to teastore-webui [{1,5,10,15,20,30,45}m-1h]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[1m])) by (destination_service)",
     "legendFormat": "{{response_code}} [1m]"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[5m])) by (destination_service)",
     "legendFormat": "{{response_code}} [5m]"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[10m])) by (destination_service)",
     "legendFormat": "{{response_code}} [10m]"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[15m])) by (destination_service)",
     "legendFormat": "{{response_code}} [15m]"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[20m])) by (destination_service)",
     "legendFormat": "{{response_code}} [20m]"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[30m])) by (destination_service)",
     "legendFormat": "{{response_code}} [30m]"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[45m])) by (destination_service)",
     "legendFormat": "{{response_code}} [45m]"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[1h])) by (destination_service)",
     "legendFormat": "{{response_code}} [1h]"
    }
   ]
  },
  {
   "title": "Total requests to teastore-webui [{1,5,10,15,20,30,45}m-1h] (same as rate???)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[1m]))"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[10m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[15m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[15m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[20m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[30m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[45m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Service Units (SU) Used", "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 } },
  {
   "title": "Median Service Units {1,5,10,15,20,30,45}m, 1h",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "SUs" } },
   "targets": [
    { "expr": "median_service_units_1m", "legendFormat": "__auto" },
    { "expr": "median_service_units_5m", "legendFormat": "__auto" },
    { "expr": "median_service_units_10m", "legendFormat": "__auto" },
    { "expr": "median_service_units_15m", "legendFormat": "__auto" },
    { "expr": "median_service_units_20m", "legendFormat": "__auto" },
    { "expr": "median_service_units_30m", "legendFormat": "__auto" },
    { "expr": "median_service_units_45m", "legendFormat": "__auto" },
    { "expr": "median_service_units_1h", "legendFormat": "__auto" }
   ]
  },
  { "gridPos": { "h": 5, "w": 20, "x": 0, "y": 20 } },
  {
   "title": "Teastore Containers Count (Default Namespace)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"default\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Teastore Container CPU Usage (Default Namespace)",
   "type": "timeseries",
   "description": "% utilization of available CPU\n(CPU seconds/second) / [available](CPU seconds/second)",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='default'}[1m])) by (namespace)",
     "legendFormat": "Teastore (all)"
    }
   ]
  },
  {
   "title": "TeaStore CPU Usage SUs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Teastore Memory Usage (Default Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (rate(container_memory_working_set_bytes{namespace=\"default\"}[1m])) by (namespace) ",
     "legendFormat": "Teastore (all)"
    }
   ]
  },
  {
   "title": "TeaStore Memory Usage SUs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace='default'} / (4 * 1024 * 1024 * 1024))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Teastore Container CPU Usage (Default Namespace)",
   "type": "timeseries",
   "description": "% utilization of available CPU\n(CPU seconds/second) / [available](CPU seconds/second)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='default'}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Teastore Memory Usage (Default Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_memory_working_set_bytes{namespace=\"default\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitoring Stack CPU Usage (Monitoring Namespace)",
   "type": "timeseries",
   "description": "CPU seconds",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"monitoring\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Monitoring Stack Memory Usage (Monitoring Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"monitoring\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "timeseries",
   "description": "CPU seconds",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod!=\"\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod!=''})",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}