{
 "title": "NISLAB Monitoring",
 "description": "NISLAB",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "State-Aware Attack",
   "type": "timeseries",
   "description": "1 is to inject traffic",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "state_aware_attack", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rate of requests to teastore-webui [{1,5,10,15,20,30,45}m-1h]",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 }
  },
  {
   "title": "Classified (Success/Error) Rate of Requests [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\",response_code=~\"[23]\\\\d{2}\"}[1m]))",
     "legendFormat": "Success Codes: 2xx, 3xx"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\",response_code=~\"(0|[45]\\\\d{2})\"}[1m]))",
     "legendFormat": "Error Codes: 0, 4xx, 5xx"
    }
   ]
  },
  { "title": "Service Units (SU) Used", "gridPos": { "h": 20, "w": 24, "x": 0, "y": 18 } },
  { "title": "Service Units (SU) Used", "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 } },
  {
   "title": "Teastore Containers Count (Default Namespace)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 }
  },
  {
   "title": "Teastore Container CPU Usage (Default Namespace)",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 45 }
  },
  {
   "title": "TeaStore CPU Usage SUs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Teastore Memory Usage (Default Namespace)",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 45 }
  },
  {
   "title": "TeaStore Memory Usage SUs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace='default'} / (4 * 1024 * 1024 * 1024))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Teastore Container CPU Usage (Default Namespace)",
   "type": "timeseries",
   "description": "% utilization of available CPU\n(CPU seconds/second) / [available](CPU seconds/second)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='default'}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Teastore Memory Usage (Default Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_memory_working_set_bytes{namespace=\"default\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitoring Stack CPU Usage (Monitoring Namespace)",
   "type": "timeseries",
   "description": "CPU seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"monitoring\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Monitoring Stack Memory Usage (Monitoring Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"monitoring\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "timeseries",
   "description": "CPU seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod!=\"\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod!=''})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Median Service Units {1,5,10,15,20,30,45}m, 1h",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 }
  },
  {
   "title": "Total requests to teastore-webui [{1,5,10,15,20,30,45}m-1h] (same as rate???)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[1m]))"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[10m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[15m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[15m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[20m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[30m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[45m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=\"teastore-webui\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}