{
 "title": "monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of Teastore Pods (Default Namespace)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_info{namespace=\"default\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Teastore Containers (Default Namespace)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_container_info{namespace=\"default\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Summed Teastore Pod CPU Usage (Default Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"default\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Individual Teastore Container CPU Usage (Default Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"default\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}