apiVersion: v1
kind: Service
metadata:
    name: coinflip-service
    namespace: monitoring
spec:
    type: ClusterIP
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
    selector:
        app: coinflip-deployment
