apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-metrics-server-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-metrics-server-deployment
  template:
    metadata:
      labels:
        app: external-metrics-server-deployment
    spec:
      containers:
        - name: external-metrics-server-deployment
          image: jilinnn/external-metrics-server # Replace with your Docker image path.
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: external-metrics-server-service
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: external-metrics-server-deployment
