apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-metrics-server
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-metrics-server
  template:
    metadata:
      labels:
        app: external-metrics-server
    spec:
      containers:
        - name: external-metrics-server
          image: jilinnn/external-metrics-server:latest # Replace with your Docker image path.
          resources:
            requests:
              cpu: "800m"
              memory: "1G"
            limits:
              memory: "2G"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: external-metrics-server-service
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: external-metrics-server
